[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dagster-dbt>=0.27.14",
    "dagster-dg-cli>=1.11.14",
    "dbt-core>=1.10.13",
    "dbt-duckdb>=1.9.6",
]
